lib/AppBundle/Entity/Vote.php
<?php
/**
 * Created by PhpStorm.
 * User: kborc
 * Date: 04.03.2019
 * Time: 16:45
 */

namespace AppBundle\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\VoteRepository")
 * @ORM\Table(name="vote")
 *
 */
class Vote
{

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Voting", inversedBy="votes")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $voting;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="votes")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $user;

    /**
     * @ORM\Column(type="integer")
     */
    protected $value;

    /**
     * @var DateTime $votedAt
     *
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    protected $votedAt;

    /**
     * @return Voting
     */
    public function getVoting()
    {
        return $this->voting;
    }

    /**
     * @param Voting $voting
     */
    public function setVoting($voting)
    {
        $this->voting = $voting;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * @param mixed $value
     */
    public function setValue($value)
    {
        $this->value = $value;
    }

    /**
     * @return DateTime
     */
    public function getVotedAt()
    {
        return $this->votedAt;
    }

    /**
     * @param DateTime $votedAt
     */
    public function setVotedAt($votedAt)
    {
        $this->votedAt = $votedAt;
    }

}

lib/AppBundle/Entity/Voting.php
<?php
/**
 * Created by PhpStorm.
 * User: Konstantin Borchert
 * Date: 14.05.2019
 * Time: 21:25
 */

namespace AppBundle\Entity;

use AppBundle\Enum\VotingEnum;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\VotingRepository")
 * @ORM\Table(name="voting")
 *
 */

class Voting
{

    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Initiative", inversedBy="votings")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $initiative;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Vote", mappedBy="voting")
     */
    protected $votes;

    /**
     *
     * @Assert\NotBlank(message="Type should be selected")
     * @ORM\Column(type="smallint", nullable=false)
     */
    protected $type;

    /**
     *
     * @Assert\NotBlank(message="State should be selected")
     * @ORM\Column(type="smallint", nullable=false)
     */
    protected $state;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $startdate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $enddate;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $quorum;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $consensus;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $eligibleVoters;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $votesTotal;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $votesTotalDelegated;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $votesRejection;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $votesRejectionDelegated;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $votesAcception;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $votesAcceptionDelegated;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $votesAbstention;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    protected $votesAbstentionDelegated;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $accepted;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $rejected;

    /**
     * Voting constructor.
     */
    public function __construct()
    {
        $this->votes = new ArrayCollection();
        $this->quorum = VotingEnum::QUORUM;
        $this->consensus = VotingEnum::CONSENSUS;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return Initiative
     */
    public function getInitiative()
    {
        return $this->initiative;
    }

    /**
     * @param Initiative $initiative
     */
    public function setInitiative($initiative)
    {
        $this->initiative = $initiative;
    }

    /**
     * @return ArrayCollection
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * @param ArrayCollection $votes
     */
    public function setVotes($votes)
    {
        $this->votes = $votes;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     * @return Voting
     */
    public function setType($type)
    {
        if (!in_array($type, VotingEnum::getAvailableStates())) {
            throw new InvalidArgumentException("Invalid type");
        }

        $this->type = $type;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * @param mixed $state
     * @return Voting
     */
    public function setState($state)
    {
        if (!in_array($state, VotingEnum::getAvailableStates())) {
            throw new InvalidArgumentException("Invalid state");
        }

        $this->state = $state;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getStartdate()
    {
        return $this->startdate;
    }

    /**
     * @param mixed $startdate
     */
    public function setStartdate($startdate)
    {
        $this->startdate = $startdate;
    }

    /**
     * @return mixed
     */
    public function getEnddate()
    {
        return $this->enddate;
    }

    /**
     * @param mixed $enddate
     */
    public function setEnddate($enddate)
    {
        $this->enddate = $enddate;
    }


    public function getQuorumAxisBreakMin()
    {
        return round (2 * ($this->getEligibleVoters() * $this->getQuorum()));
    }

    public function getQuorumAxisBreakMax()
    {
        return round ($this->getEligibleVoters() - ($this->getEligibleVoters() * $this->getQuorum()));
    }

    /**
     * @return float
     */
    public function getQuorum()
    {
        return $this->quorum;
    }

    /**
     * @param float $quorum
     */
    public function setQuorum($quorum)
    {
        $this->quorum = $quorum;
    }

    /**
     * @return float
     */
    public function getConsensus()
    {
        return $this->consensus;
    }

    /**
     * @param float $consensus
     */
    public function setConsensus($consensus)
    {
        $this->consensus = $consensus;
    }

    /**
     * @return mixed
     */
    public function getVotesTotal()
    {
        return $this->votesTotal;
    }

    /**
     * @param mixed $votesTotal
     */
    public function setVotesTotal($votesTotal)
    {
        $this->votesTotal = $votesTotal;
    }

    /**
     * @return mixed
     */
    public function getVotesTotalDelegated()
    {
        return $this->votesTotalDelegated;
    }

    /**
     * @param mixed $votesTotalDelegated
     */
    public function setVotesTotalDelegated($votesTotalDelegated)
    {
        $this->votesTotalDelegated = $votesTotalDelegated;
    }

    /**
     * @return mixed
     */
    public function getVotesRejection()
    {
        return $this->votesRejection;
    }

    /**
     * @param mixed $votesRejection
     */
    public function setVotesRejection($votesRejection)
    {
        $this->votesRejection = $votesRejection;
    }

    /**
     * @return mixed
     */
    public function getVotesRejectionDelegated()
    {
        return $this->votesRejectionDelegated;
    }

    /**
     * @param mixed $votesRejectionDelegated
     */
    public function setVotesRejectionDelegated($votesRejectionDelegated)
    {
        $this->votesRejectionDelegated = $votesRejectionDelegated;
    }

    /**
     * @return mixed
     */
    public function getVotesAcception()
    {
        return $this->votesAcception;
    }

    /**
     * @param mixed $votesAcception
     */
    public function setVotesAcception($votesAcception)
    {
        $this->votesAcception = $votesAcception;
    }

    /**
     * @return mixed
     */
    public function getVotesAcceptionDelegated()
    {
        return $this->votesAcceptionDelegated;
    }

    /**
     * @param mixed $votesAcceptionDelegated
     */
    public function setVotesAcceptionDelegated($votesAcceptionDelegated)
    {
        $this->votesAcceptionDelegated = $votesAcceptionDelegated;
    }

    /**
     * @return mixed
     */
    public function getVotesAbstention()
    {
        return $this->votesAbstention;
    }

    /**
     * @param mixed $votesAbstention
     */
    public function setVotesAbstention($votesAbstention)
    {
        $this->votesAbstention = $votesAbstention;
    }

    /**
     * @return mixed
     */
    public function getVotesAbstentionDelegated()
    {
        return $this->votesAbstentionDelegated;
    }

    /**
     * @param mixed $votesAbstentionDelegated
     */
    public function setVotesAbstentionDelegated($votesAbstentionDelegated)
    {
        $this->votesAbstentionDelegated = $votesAbstentionDelegated;
    }

    /**
     * @return mixed
     */
    public function getAccepted()
    {
        return $this->accepted;
    }

    /**
     * @param mixed $accepted
     */
    public function setAccepted($accepted)
    {
        $this->accepted = $accepted;
    }

    /**
     * @return mixed
     */
    public function getRejected()
    {
        return $this->rejected;
    }

    /**
     * @param mixed $rejected
     */
    public function setRejected($rejected)
    {
        $this->rejected = $rejected;
    }

    /**
     * @return mixed
     */
    public function getEligibleVoters()
    {
        return $this->eligibleVoters;
    }

    /**
     * @param mixed $eligibleVoters
     */
    public function setEligibleVoters($eligibleVoters)
    {
        $this->eligibleVoters = $eligibleVoters;
    }

}

src/AppBundle/Entity/Vote.php
<?php
/**
 * Created by PhpStorm.
 * User: kborc
 * Date: 04.03.2019
 * Time: 16:45
 */

namespace AppBundle\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\VoteRepository")
 * @ORM\Table(name="vote")
 *
 */
class Vote
{

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Voting", inversedBy="votes")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $voting;
    
     /**
     * @ORM\Column(type="integer")
     */
    protected $value;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="votes")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $user;   

    /**
     * @return Voting
     */
    public function getVoting()
    {
        return $this->voting;
    }

    /**
     * @param Voting $voting
     */
    public function setVoting($voting)
    {
        $this->voting = $voting;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * @param mixed $value
     */
    public function setValue($value)
    {
        $this->value = $value;
    }

}

templates/Vote/_form.html.twig
{% extends 'base.html.twig' %}

{% block test %}

                        <!-- Reply Form -->



                        {{ form_start(form) }}

                        <fieldset>


                            {{ form_row(form.createdBy) }}
                            <a href="{{ path('admin_user_edit', { 'id': user.id }) }}">{{ user.id }}</a>
                            {{ form_row(form.message) }}

                            <div class="col-12">
                                <button type="submit" class="btn btn-primary" formnovalidate>Save</button>
                            </div>


                        </fieldset>


                        {{ form_end(form) }}

{% endblock %}

templates/Vote/counter.html.twig
<div class="vote_area clearfix bg-white mb-30 p-30 box-shadow">
    <!-- Section Title -->
    <div class="section-heading">
        <h5>VOTE</h5>
    </div>

    <p>The Voting is starting soon...</p>
</div>

templates/Vote/current_vote.html.twig
<div class="vote_area clearfix bg-white mb-30 p-30 box-shadow">
    <!-- Section Title -->
    <div class="section-heading">
        <h5>VOTE</h5>
    </div>

    {{ form_start(form) }}

    {{ form_row(form.voteYes) }}
    {{ form_row(form.voteAbstention) }}
    {{ form_row(form.voteNo) }}

    {{ form_end(form) }}

</div>

templates/Vote/form.html.twig
<div class="vote_area clearfix bg-white mb-30 p-30 box-shadow">
    <!-- Section Title -->
    <div class="section-heading">
        <h5>VOTE</h5>
    </div>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

</div>

templates/Vote/future_vote.html.twig
<div class="vote_area clearfix bg-white mb-30 p-30 box-shadow">
    <!-- Section Title -->
    <div class="section-heading">
        <h5>VOTE</h5>
    </div>

    {{ form_start(form) }}

    {{ form_row(form.vote) }}

    {{ form_end(form) }}

</div>

templates/Vote/link.html.twig
<div class="vote_area clearfix bg-white mb-30 p-30 box-shadow">
    <!-- Section Title -->
    <div class="section-heading">
        <h5>VOTE</h5>
    </div>

    <p>Your Initiative is still in draft mode. You can publish it {{ path('user_initiative_edit', {'id': initiative.id, 'slug': initiative.slug }) }}</p>

</div>

templates/Vote/result.html.twig
{% extends 'base.html.twig' %}

{% import 'Widget/macros.html.twig' as m %}

{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: 'Results', background: asset('assets/img/header/statistics_large.jpg')}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

    <section class="wpe-content-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">

                    <div class="vote_area clearfix bg-white mb-30 p-30 box-shadow">

                        {% if future.state is defined and future.state == 2 %}
                            <div class="section-heading">
                                <h5>Proposal Stage</h5>
                            </div>

                            <div id="chartdiv_future" style="width: 100%; height: 400px;"></div>
                        {% endif %}

                        {% if current.state is defined and current.state == 2 %}
                            <div class="section-heading">
                                <h5>Vote Stage</h5>
                            </div>

                            <div id="chartdiv_current" style="width: 100%; height: 400px;"></div>
                        {% endif %}


                    </div>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block javascripts %}

    {{ parent() }}

    <script src="{{ asset('assets/plugins/underscore/underscore.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/vote.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/plugins/amcharts4/core.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/plugins/amcharts4/charts.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/plugins/amcharts4/themes/animated.js') }}" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            {% if future.state is defined and future.state == 2 %}
            function future() {

                if ($('#chartdiv_future').length) {

                    am4core.useTheme(am4themes_animated);

                    var chart = am4core.create("chartdiv_future", am4charts.XYChart3D);

                    chart.dataSource.url = Routing.generate('initiative_result_data_future', {
                        'id': {{ initiative.id }},
                        'slug': '{{ initiative.slug }}'
                    });
                    chart.dataSource.parser = new am4core.JSONParser();
                    chart.dataSource.parser.options.emptyAs = 0;
                    chart.dataSource.events.on("error", function (ev) {
                        console.log("Oopsy! Something went wrong");
                    });

                    chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

                    // Create axes
                    var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                    categoryAxis.dataFields.category = "vote";
                    categoryAxis.renderer.grid.template.location = 0;
                    categoryAxis.renderer.minGridDistance = 30;

                    var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                    valueAxis.title.text = "Voters";
                    valueAxis.title.fontWeight = 800;

                    var axisBreak = valueAxis.axisBreaks.create();
                    axisBreak.startValue = {{ future.quorumAxisBreakMin }};
                    axisBreak.endValue = {{ future.quorumAxisBreakMax }};
                    axisBreak.breakSize = 0.025;


                    var series = chart.series.push(new am4charts.ColumnSeries3D());
                    series.dataFields.valueY = "voters";
                    series.dataFields.categoryX = "vote";
                    series.columns.template.width = am4core.percent(20);
                    series.columns.template.strokeWidth = 2;
                    series.dataFields.dummyData = "breakdown";
                    series.tooltipText = "[bold white font-size: 20px]{vote}[/]\ntotal: [bold]{voters}[/]\ndirect: [bold]{dummyData.direct}[/]\ndelegated: [bold]{dummyData.delegated}[/]";
                    series.clustered = false;

                    var series2 = chart.series.push(new am4charts.ColumnSeries3D());
                    series2.dataFields.valueY = "quorum";
                    series2.dataFields.categoryX = "vote";
                    series2.columns.template.width = am4core.percent(30);
                    series2.columns.template.fillOpacity = 0.6;
                    series2.columns.template.strokeOpacity = 1;
                    series2.columns.template.strokeWidth = 2;
                    series2.dataFields.dummyData = "breakdown";
                    series2.tooltipText = "[bold white font-size: 20px]Quorum[/]\nvotes needed: [bold]{valueY}[/]";
                    series2.clustered = false;

                    var series3 = chart.series.push(new am4charts.ColumnSeries3D());
                    series3.dataFields.valueY = "eligible";
                    series3.dataFields.categoryX = "vote";
                    series3.columns.template.width = am4core.percent(30);
                    series3.columns.template.fillOpacity = 0.6;
                    series3.columns.template.strokeOpacity = 1;
                    series3.columns.template.strokeWidth = 2;
                    series3.dataFields.dummyData = "breakdown";
                    series3.tooltipText = "[bold white font-size: 20px]Citizens[/]\ntotal: [bold black]{eligible}[/]";
                    series3.clustered = false;

                    chart.cursor = new am4charts.XYCursor();
                    chart.cursor.lineX.disabled = true;
                    chart.cursor.lineY.disabled = true;
                }
            }

            future();

            {% endif %}

            {% if current.state is defined and current.state == 2 %}
            function current() {

                if ($('#chartdiv_current').length) {

                    am4core.useTheme(am4themes_animated);

                    var chart = am4core.create("chartdiv_current", am4charts.PieChart3D);

                    chart.dataSource.url = Routing.generate('initiative_result_data_current', {
                        'id': {{ initiative.id }},
                        'slug': '{{ initiative.slug }}'
                    });
                    chart.dataSource.parser = new am4core.JSONParser();
                    chart.dataSource.parser.options.emptyAs = 0;
                    chart.dataSource.events.on("error", function (ev) {
                        console.log("Oopsy! Something went wrong");
                    });

                    chart.hiddenState.properties.opacity = 0; // this creates initial fade-in
                    chart.innerRadius = am4core.percent(30);
                    chart.depth = 60;

                    // Add and configure Series
                    var pieSeries = chart.series.push(new am4charts.PieSeries3D());

                    pieSeries.colors.list = [
                        am4core.color("#54c292"),
                        am4core.color("#fffe5e"),
                        am4core.color("#ff738f")
                    ];

                    pieSeries.dataFields.value = "voters";
                    pieSeries.dataFields.depthValue = "voters";
                    pieSeries.dataFields.category = "vote";
                    // pieSeries.dataFields.value = "litres";
                    // pieSeries.dataFields.category = "country";
                    pieSeries.slices.template.stroke = am4core.color("#fff");
                    pieSeries.slices.template.strokeWidth = 2;
                    pieSeries.slices.template.strokeOpacity = 1;
                    // pieSeries.slices.template.cornerRadius = 5;
                    // pieSeries.colors.step = 3;

                    pieSeries.slices.template.propertyFields.dummyData = "breakdown";
                    pieSeries.slices.template.tooltipText = "[bold white font-size: 20px]{vote} ({value.percent.formatNumber('#.#')}%)[/]\ntotal:[bold]{voters}[/]\ndirect: [bold]{dummyData.direct}[/]\ndelegated: [bold]{dummyData.delegated}[/]\nenddate: [bold]{dummyData.enddate}[/]\naccepted: [bold]{dummyData.accepted}[/]";

                    pieSeries.slices.template.configField = "config";

                    // Disabling labels and ticks on inner circle
                    // pieSeries.labels.template.disabled = true;
                    // pieSeries.ticks.template.disabled = true;

                    // Disable sliding out of slices
                    pieSeries.slices.template.states.getKey("hover").properties.shiftRadius = 0;
                    pieSeries.slices.template.states.getKey("hover").properties.scale = 1.1;


                    // This creates initial animation
                    pieSeries.hiddenState.properties.opacity = 1;
                    pieSeries.hiddenState.properties.endAngle = -90;
                    pieSeries.hiddenState.properties.startAngle = -90;
                }
            }

            current();
            {% endif %}


        });
    </script>

{% endblock %}

templates/Vote/test.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <!-- ##### Breadcrumb Area Start ##### -->
    <section class="breadcrumb-area bg-img bg-overlay" style="background-image: url('https://via.placeholder.com/1920x850');">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="breadcrumb-content">
                        <h2>New Initiative</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Breadcrumb Area End ##### -->

    <!-- ##### Login Area Start ##### -->
    <div class="mag-login-area py-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="login-content bg-white p-30 box-shadow">
                        <!-- Section Title -->
                        <div class="section-heading">
                            <h5>New Initiative!</h5>
                        </div>

                        {{ form_start(form) }}


                        {{ form_row(form.message) }}



                        <button type="submit" class="btn btn-primary" formnovalidate>Save</button>
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </div>
        <!-- ##### Login Area End ##### -->
    </div>
{% endblock body %}
{% block javascripts %}
    {{ parent() }}
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}

templates/Vote/vote.html.twig
<div class="vote_area clearfix bg-white mb-30 p-30 box-shadow">
    <!-- Section Title -->
    <div class="section-heading">
        <h5>VOTE</h5>
    </div>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

</div>