lib/AppBundle/Entity/Category.php
<?php
/**
 * Created by PhpStorm.
 * User: kborc
 * Date: 04.03.2019
 * Time: 15:53
 */

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation as JMSSerializer;
use Symfony\Component\String\Slugger\SluggerInterface;
use Gedmo\Mapping\Annotation as Gedmo;
use AppBundle\Enum\CategoryEnum;

/**
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CategoryRepository")
 * @ORM\Table(name="category")
 *
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Initiative", mappedBy="category", cascade={"remove"})
     */
    private $initiatives;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Delegation", mappedBy="category")
     */
    private $delegations;

    /**
     * @Assert\NotBlank(message="Name for the category is mandatory")
     * @ORM\Column(type="string")
     * @JMSSerializer\Expose
     * @JMSSerializer\Type("string")
     * @JMSSerializer\Groups({"default", "simple"})
     */
    protected $name;

    /**
     * @ORM\Column(type="text", nullable=true)     *
     */
    protected $description;

    /**
     *
     * @Assert\NotBlank(message="Type should be selected")
     * @ORM\Column(type="smallint", nullable=false)
     * @JMSSerializer\Expose
     * @JMSSerializer\Type("integer")
     * @JMSSerializer\Groups({"default", "simple"})
     */
    protected $type;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @JMSSerializer\Type("string")
     * @JMSSerializer\Groups({"default", "simple"})
     */
    protected $country;

    /**
     * @ORM\Column(type="string", unique=true)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;


    /**
     * Category constructor.
     */
    public function __construct()
    {
        $this->initiatives = new ArrayCollection();
        $this->delegations = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return ArrayCollection
     */
    public function getInitiatives()
    {
        return $this->initiatives;
    }

    /**
     * @param ArrayCollection $initiatives
     */
    public function setInitiatives($initiatives)
    {
        $this->initiatives = $initiatives;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug(SluggerInterface $slugger): self
    {
        $this->slug = $slugger->slug($this->name);

        return $this;
    }

    /**
     * @return string
     */
    public function getImage(){
        return $this->getImageLarge();
    }

    /**
     * @return string
     */
    public function getImageLarge(){
        return '/assets/img/category/K_' . $this->getId() . '_large.jpg';
    }

    /**
     * @return string
     */
    public function getImageSmall(){
        return '/assets/img/category/K_' . $this->getId() . '_small.jpg';
    }

        /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     * @return Initiative
     */

    public function setType($type)
    {
        if (!in_array($type, CategoryEnum::getAvailableTypes())) {
            throw new \InvalidArgumentException("Invalid type");
        }

        $this->type = $type;

        return $this;
    }

    /**
     * @return string
     */

    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }


}

lib/AppBundle/Form/CategoryForm.php
<?php

namespace AppBundle\Form;


use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use AppBundle\Enum\CategoryEnum;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\TextareaType;


class CategoryForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder


            ->add('name', TextType::class, array('label' => 'category.edit.name'))
            ->add('description',
                CKEditorType::class, array(
                    'config' => array(
                        'uiColor' => '#ffffff',
                        //...
                    )))
            ->add('type', ChoiceType::class, [
                'label' => 'category.edit.type',
                'required' => true,
                'choices' => CategoryEnum::getAvailableTypes(),
                // 'choices_as_values' => true,
                'choice_label' => function($choice) {
                    return CategoryEnum::getTypeName($choice);
                }
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'AppBundle\Entity\Category'
        ]);
    }

    public function getBlockPrefix()
    {
        return 'app_bundle_category_form';
    }
}

lib/AppBundle/Controller/CategoryController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Category;
use AppBundle\Entity\Initiative;
use JMS\Serializer\SerializerInterface;
use AppBundle\Enum\InitiativeEnum;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use APY\BreadcrumbTrailBundle\Annotation\Breadcrumb;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\Persistence\ManagerRegistry;

/**
 * Category controller.
 *
 * @Route("/category")
 */
class CategoryController extends BaseController
{

    public function __construct(SerializerInterface $serializer,ManagerRegistry $managerRegistry)
    {
        parent::__construct($serializer,$managerRegistry);
        $this->_serializeGroups = ["simple"];
    }

    /**
     * @Breadcrumb("breadcrumb.{type}.label", attributes={"translate": true})
     * @Route("/{type}", requirements={"type" = "(future|current|past|program)"}, name="category_index")
     */

    public function listCategoryOverviewAction($type)
    {
        // dd($type);
        $em = $this->managerRegistry->getManager();

        if ($type === 'future') {

            $initiatives = $em->getRepository(Category::class)
                ->getFutureInitiatives();

            return $this->render('Category/future.html.twig', [
                'initiatives' => $initiatives,
                'type' => $type,
                'alias' => 'proposals',
            ]);

        } elseif ($type === 'current') {
            $initiatives = $em->getRepository(Category::class)
                ->getCurrentInitiatives();

            return $this->render('Category/current.html.twig', [
                'initiatives' => $initiatives,
                'type' => $type,
                'alias' => 'votes',
            ]);

        } elseif ($type === 'program') {
            $categories = $em->getRepository(Category::class)
                ->getCategoryOverview($type);

            return $this->render('Category/index.html.twig', [
                'categories' => $categories,
                'type' => $type,
                'alias' => 'decisions',
            ]);
        } else {
            $categories = $em->getRepository(Category::class)
                ->getCategoryOverview($type);
    
            return $this->render('Category/index.html.twig', [
                'categories' => $categories,
                'type' => $type,
                'alias' => 'archive',
            ]);
        }
    }

    /**
     * @Breadcrumb("breadcrumb.{type}.label", route={"name"="category_index", "parameters"={"type"="{type}"}}, attributes={"translate": true})
     * @Breadcrumb("{category.name}")
     * @Route("/{type}/{id}/{slug}", requirements={"id" = "\d+","type" = "(future|current|past|program)"}, name="category_type")
     * @param Category $category {type}
     * @param $type
     * @return Response
     */
    public function listCategoryAction(int $id, $type)
    {
        $em = $this->managerRegistry->getManager();
        $category = $em->getRepository(Category::class)->find($id);

        if ($type === 'program') {
            return $this->render('Category/category.html.twig', [
                'category' => $category,
                'type' => $type,
                'alias' => 'adopted votes'
            ]);
        } elseif ($type === 'past') {
            return $this->render('Category/category.html.twig', [
                "category" => $category,
                "type" => $type,
                'alias' => 'unsuccessful votes'
            ]);
        } elseif ($type === 'current') {
            
            $initiatives = $em->getRepository(Category::class)
            ->getInitiatives($category, InitiativeEnum::TYPE_CURRENT);
            
            return $this->render('Category/current.html.twig', [
                'category' => $category,
                'type' => $type,
                'alias' => 'votes',
                'initiatives' => $initiatives,
            ]);
        } elseif ($type === 'future') {

            $initiatives = $em->getRepository(Category::class)
            ->getInitiatives($category, InitiativeEnum::TYPE_FUTURE);

            return $this->render('Category/future.html.twig', [
                'category' => $category,
                'type' => $type,
                'alias' => 'proposals',
                'initiatives' => $initiatives,
            ]);
        }
    }

    /**
     * Lists all initiative entities of certain type.
     *
     * @Route("/{type}/{id}/{slug}/ajax", name="category_type_search", requirements={"type" = "(future|current|past|program)"},defaults={"id" = 0}, methods={"POST","GET"}, options={"expose"=true})
     * @param Request $request
     * @param Category $category
     * @param $type
     * @return JsonResponse
     */
    public function listCategorySearchAction(Request $request, int $id, $type)
    {

        $em = $this->managerRegistry->getManager();
        $category = $em->getRepository(Category::class)->find($id);

        $draw = $request->request->getInt('draw', 1);
        $start = $request->request->getInt('start', 0);
        $search = $request->request->get('search');
        $length = $request->request->getInt('length', 10);
        $columns = $request->request->get('columns');
        $order = $request->request->get('order');
        $idx = $order[0]['column'];
        $orderBy = preg_replace('/^title/', 'i.title', $columns[$order[0]['column']]['data']);
        $orderBy = preg_replace('/^createdBy.username/', 'c.username', $orderBy);
        $orderBy = preg_replace('/^createdAt/', 'i.createdAt', $orderBy);
        $orderDir = $order[0]['dir'];

        $initiatives = $em->getRepository(Initiative::class)->searchCategoryType($search['value'], $orderBy, $orderDir, $category,$type);

        $output = array();
        $output['draw'] = $draw;
        try {
            $output['recordsTotal'] = $em->getRepository(Initiative::class)->countAllTypeInitiatives($category,$type);
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
        $output["recordsFiltered"] = count($initiatives);

        $output['items'] = array_splice($initiatives, $start, $length);
        $response = $this->createApiResponse($output, 200);

        return $response;

    }


    /**
     * Lists all category entities.
     *
     * @Route("/delegatec", name="category_delegate", methods={"GET"})
     * @return Response
     */
    public function indexAction()
    {

        $em = $this->managerRegistry->getManager();
        $categories = $em->getRepository(Category::class)->findAll();

        return $this->render('Delegation/category.html.twig', array(
            'categories' => $categories,
        ));
    }

}

templates/Category/category.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: alias|capitalize, background: asset(category.image)}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

    <div class="wpe-content-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="default-content bg-white mb-30 p-30 box-shadow">
                        <!-- Section Title -->
                        <div class="section-heading">
                            <h5>{{ alias|capitalize }}</h5>
                            <h5>{{ category.name }}</h5>
                        </div>

                        <table id="category" class="table table-striped table-bordered"
                               data-category-id="{{ category.id }}"
                               data-category-slug="{{ category.slug }}"
                               data-type="{{ type }}"
                               style="width:100%">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Creator</th>
                                <th>Date</th>
                                <th>&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/assets/plugins/DataTables/datatables.min.css') }}"/>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('/assets/plugins/DataTables/datatables.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            var app = App.getInstance();
            app.configureDTCategory($('#category'));
        });
    </script>
{% endblock %}

templates/Category/current.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: 'Ongoing Votes', background: '/assets/img/header/current_large.jpg'}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

    <div class="wpe-content-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="default-content bg-white mb-30 p-30 box-shadow">
                        <!-- Section Title -->
                        <div class="section-heading">
                            <h6>Votes</h6>
                        </div> 
                            <table class="table table-categories table-striped table-bordered" style="width:100%">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Creator</th>
                                    <th>Category</th>
                                    <th>Date</th>
                                    <th>Views</th>
                                    <th>Comments</th>
                                    <th>Voting</th>
                                </tr>
                                </thead>
                                <tbody>                  
                                {% if app.user %}
                                    {% for category in initiatives %}
                                        {% if app.user.country == category.description or category.description|length > 2 %}
                                            {% for initiative in category.initiatives %}
                                                <tr>
                                                    <td>
                                                        <p><a href="{{ path('initiative_show', { 'id': initiative.id, 'slug': initiative.slug }) }}">{{ initiative.title }}</a></p>
                                                    </td>
                                                    <td><a href="{{ path('user_profile_show', { 'id': initiative.createdBy.id }) }}"><img src="{{ path('user_profile_avatar', { 'id': initiative.createdBy.id }) }}" class="small-user-avatar mr-2">{{ initiative.createdBy }}</a></td>
                                                    <td>{{ category.name }}</td>
                                                    <td>{{ initiative.createdAt|date('Y-m-d') }}</td>
                                                    <td>{{ initiative.views }}</td>
                                                    <td>{{ initiative.countComments }}</td>
                                                    <td class="text-center">
                                                        {% if initiative.voteStatus == 'now' %}
                                                            <span class="badge badge-danger"> NOW </span>
                                                        {% elseif initiative.voteStatus == 'soon' %}
                                                            <span class="badge badge-warning"> SOON </span>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                                {% else %}                              
                                    {% for category in initiatives %}
                                        {% if category.description|length > 2 %}
                                            {% for initiative in category.initiatives %}
                                                <tr>
                                                    <td>
                                                        <p><a href="{{ path('initiative_show', { 'id': initiative.id, 'slug': initiative.slug }) }}">{{ initiative.title }}</a></p>
                                                    </td>
                                                    <td><a href="{{ path('user_profile_show', { 'id': initiative.createdBy.id }) }}"><img src="{{ path('user_profile_avatar', { 'id': initiative.createdBy.id }) }}" class="small-user-avatar mr-2">{{ initiative.createdBy }}</a></td>
                                                    <td>{{ category.name }}</td>
                                                    <td>{{ initiative.createdAt|date('Y-m-d') }}</td>
                                                    <td>{{ initiative.views }}</td>
                                                    <td>{{ initiative.countComments }}</td>
                                                    <td class="text-center">
                                                        {% if initiative.voteStatus == 'now' %}
                                                            <span class="badge badge-danger"> NOW </span>
                                                        {% elseif initiative.voteStatus == 'soon' %}
                                                            <span class="badge badge-warning"> SOON </span>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                    </tbody>
                                {% endif %}
                         </table>  
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="/assets/plugins/DataTables/datatables.min.cs"/>
{% endblock %}

{% block javascripts %}
{{ parent() }}
    <script type="text/javascript" src="/assets/plugins/DataTables/datatables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('.table-categories').DataTable({
                initComplete: function () {
                    this.api().order( [[ 3, 'desc' ], [ 5, 'desc' ], [ 4, 'desc' ]] )
                    this.api().draw()
                    this.api().columns([2]).every( function () {
                        var column = this;
                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.header()) )
                            .on( 'change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
        
                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );
        
                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    } );           
                }
            });
        });
    </script>

{% endblock %}

templates/Category/future.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: 'Agenda Setting', background: '/assets/img/header/initiative_large.jpg'}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

    <div class="wpe-content-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="default-content bg-white mb-30 p-30 box-shadow">
                        <!-- Section Title -->
                        <div class="section-heading">
                            <h6>Proposals</h6>
                        </div> 
                            <table class="table table-categories table-striped table-bordered" style="width:100%">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Creator</th>
                                    <th>Category</th>
                                    <th>Date</th>
                                    <th>Views</th>
                                    <th>Comments</th>
                                    <th>Supporters</th>
                                </tr>
                                </thead>
                                <tbody>                  
                                {% if app.user %}
                                    {% for category in initiatives %}
                                        {% if app.user.country == category.description or category.description|length > 2 %}
                                            {% for initiative in category.initiatives %}
                                                <tr>
                                                    <td>
                                                        <p><a href="{{ path('initiative_show', { 'id': initiative.id, 'slug': initiative.slug }) }}">{{ initiative.title }}</a></p>
                                                    </td>
                                                    <td><a href="{{ path('user_profile_show', { 'id': initiative.createdBy.id }) }}"><img src="{{ path('user_profile_avatar', { 'id': initiative.createdBy.id }) }}" class="small-user-avatar mr-2">{{ initiative.createdBy }}</a></td>
                                                    <td>{{ category.name }}</td>
                                                    <td>{{ initiative.createdAt|date('Y-m-d') }}</td>
                                                    <td>{{ initiative.views }}</td>
                                                    <td>{{ initiative.countComments }}</td>
                                                    <td class="text-center">
                                                        {% if initiative.voteStatus == 'now' %}
                                                            {{ initiative.getFutureVoting.getVotesTotal() }}
                                                            {# <span class="badge badge-danger"> NOW </span> #}
                                                        {% elseif initiative.voteStatus == 'soon' %}
                                                            <span class="badge badge-warning"> STARTING SOON </span>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                                {% else %}                              
                                    {% for category in initiatives %}
                                        {% if category.description|length > 2 %}
                                            {% for initiative in category.initiatives %}
                                                <tr>
                                                    <td>
                                                        <p><a href="{{ path('initiative_show', { 'id': initiative.id, 'slug': initiative.slug }) }}">{{ initiative.title }}</a></p>
                                                    </td>
                                                    <td><a href="{{ path('user_profile_show', { 'id': initiative.createdBy.id }) }}"><img src="{{ path('user_profile_avatar', { 'id': initiative.createdBy.id }) }}" class="small-user-avatar mr-2">{{ initiative.createdBy }}</a></td>
                                                    <td>{{ category.name }}</td>
                                                    <td>{{ initiative.createdAt|date('Y-m-d') }}</td>
                                                    <td>{{ initiative.views }}</td>
                                                    <td>{{ initiative.countComments }}</td>
                                                    <td class="text-center">
                                                        {% if initiative.voteStatus == 'now' %}
                                                            {{ initiative.getFutureVoting.getVotesTotal() }}
                                                            {# <span class="badge badge-danger"> NOW </span> #}
                                                        {% elseif initiative.voteStatus == 'soon' %}
                                                            <span class="badge badge-warning"> STARTING SOON </span>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                    </tbody>
                                {% endif %}
                         </table>  
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="/assets/plugins/DataTables/datatables.min.css"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="/assets/plugins/DataTables/datatables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('.table-categories').DataTable({
                initComplete: function () {
                    this.api().order( [[ 4, 'desc' ], [ 5, 'desc' ], [ 3, 'desc' ]] )
                    this.api().draw()
                    this.api().columns([2]).every( function () {
                        var column = this;
                        var select = $('<select><option value=""></option></select>')
                            .appendTo( $(column.header()) )
                            .on( 'change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
        
                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );
        
                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    } );           
                }
            });
        });
    </script>

{% endblock %}