lib/AppBundle/Entity/Category.php
<?php
/**
 * Created by PhpStorm.
 * User: kborc
 * Date: 04.03.2019
 * Time: 15:53
 */

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation as JMSSerializer;
use Symfony\Component\String\Slugger\SluggerInterface;
use Gedmo\Mapping\Annotation as Gedmo;
use AppBundle\Enum\CategoryEnum;

/**
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CategoryRepository")
 * @ORM\Table(name="category")
 *
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Initiative", mappedBy="category", cascade={"remove"})
     */
    private $initiatives;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Delegation", mappedBy="category")
     */
    private $delegations;

    /**
     * @Assert\NotBlank(message="Name for the category is mandatory")
     * @ORM\Column(type="string")
     * @JMSSerializer\Expose
     * @JMSSerializer\Type("string")
     * @JMSSerializer\Groups({"default", "simple"})
     */
    protected $name;

    /**
     * @ORM\Column(type="text", nullable=true)     *
     */
    protected $description;

    /**
     *
     * @Assert\NotBlank(message="Type should be selected")
     * @ORM\Column(type="smallint", nullable=false)
     * @JMSSerializer\Expose
     * @JMSSerializer\Type("integer")
     * @JMSSerializer\Groups({"default", "simple"})
     */
    protected $type;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @JMSSerializer\Type("string")
     * @JMSSerializer\Groups({"default", "simple"})
     */
    protected $country;

    /**
     * @ORM\Column(type="string", unique=true)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;


    /**
     * Category constructor.
     */
    public function __construct()
    {
        $this->initiatives = new ArrayCollection();
        $this->delegations = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return ArrayCollection
     */
    public function getInitiatives()
    {
        return $this->initiatives;
    }

    /**
     * @param ArrayCollection $initiatives
     */
    public function setInitiatives($initiatives)
    {
        $this->initiatives = $initiatives;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug(SluggerInterface $slugger): self
    {
        $this->slug = $slugger->slug($this->name);

        return $this;
    }

    /**
     * @return string
     */
    public function getImage(){
        return $this->getImageLarge();
    }

    /**
     * @return string
     */
    public function getImageLarge(){
        return '/assets/img/category/K_' . $this->getId() . '_large.jpg';
    }

    /**
     * @return string
     */
    public function getImageSmall(){
        return '/assets/img/category/K_' . $this->getId() . '_small.jpg';
    }

        /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     * @return Initiative
     */

    public function setType($type)
    {
        if (!in_array($type, CategoryEnum::getAvailableTypes())) {
            throw new \InvalidArgumentException("Invalid type");
        }

        $this->type = $type;

        return $this;
    }

    /**
     * @return string
     */

    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }


}

lib/AppBundle/Entity/Favourite.php
<?php


namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Enum\FavouriteEnum;
use Symfony\Component\Validator\Constraints as Assert;


/**
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\FavouriteRepository")
 * @ORM\Table(name="favourite")
 *
 */

class Favourite
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="favourites")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $user;

    /**
     *
     * @Assert\NotBlank(message="Type should be selected")
     * @ORM\Column(type="smallint", nullable=false)
     */
    protected $type;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="friends")
     * @ORM\JoinColumn(nullable=true)
     */
    protected $friend;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Initiative", inversedBy="favourites")
     * @ORM\JoinColumn(nullable=true)
     */
    protected $initiative;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @return mixed|string
     */
    public function getTypeName()
    {
        return FavouriteEnum::getTypeName($this->type);
    }

    /**
     * @param mixed $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getFriend()
    {
        return $this->friend;
    }

    /**
     * @param mixed $friend
     */
    public function setFriend($friend)
    {
        $this->friend = $friend;
    }

    /**
     * @return mixed
     */
    public function getInitiative()
    {
        return $this->initiative;
    }

    /**
     * @param mixed $initiative
     */
    public function setInitiative($initiative)
    {
        $this->initiative = $initiative;
    }

}

lib/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Category;
use AppBundle\Entity\Comment;
use AppBundle\Entity\Initiative;
use JMS\Serializer\SerializerInterface;
use AppBundle\Entity\User;
use AppBundle\Repository\UserRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

use Exception;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use DateTime;
use APY\BreadcrumbTrailBundle\Annotation\Breadcrumb;
// use Symfony\Component\Cache\Adapter\FilesystemAdapter;
// use Symfony\Component\Cache\Adapter\AdapterInterface;
use Psr\Cache\CacheItemPoolInterface;
use Doctrine\Persistence\ManagerRegistry;

class DefaultController extends BaseController
{
    private $cache;
    public $serializer;

    public function __construct(SerializerInterface $serializer,CacheItemPoolInterface $cache,ManagerRegistry $managerRegistry)
    {
        parent::__construct($serializer,$managerRegistry);
        $this->cache = $cache;
        $this->_serializeGroups = ["simple"];

    }

    /**
     * @Route("/", name="homepage")
     * @param Request $request
     * @return Response
     * @throws Exception
     */

    public function indexAction(Request $request)
    {

        $em = $this->managerRegistry->getManager();

        $initiatives = $em->getRepository(Initiative::class)->slider(25);

        $votesf = $em->getRepository(Initiative::class)
            ->future();
        $votesc = $em->getRepository(Initiative::class)
            ->current();
        return $this->render('default/index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.project_dir')) . DIRECTORY_SEPARATOR,
            'votesf' => $votesf,
            'votesc' => $votesc,
            'top' => $initiatives,
        ]);

    }

    /**
     * @Breadcrumb("breadcrumb.legal.label", attributes={"translate": true})
     * @Route("/legal", name="legal_notice")
     * @param Request $request
     * @return Response
     * @throws Exception
     */

    public function legalAction(Request $request)
    {

        return $this->render('default/legal.html.twig', [
        ]);

    }

    /**
     * @Breadcrumb("breadcrumb.privacy.label", attributes={"translate": true})
     * @Route("/privacy", name="privacy")
     * @param Request $request
     * @return Response
     * @throws Exception
     */

    public function privacyAction(Request $request)
    {

        return $this->render('default/privacy.html.twig', [
        ]);

    }

    /**
     * @Breadcrumb("breadcrumb.rules.label", attributes={"translate": true})
     * @Route("/rules", name="rules")
     * @param Request $request
     * @return Response
     * @throws Exception
     */

    public function rulesAction(Request $request)
    {

        return $this->render('default/rules.html.twig', [
        ]);

    }

    /**
     * @Breadcrumb("breadcrumb.faq.label", attributes={"translate": true})
     * @Route("/faq", name="faq")
     * @param Request $request
     * @return Response
     * @throws Exception
     */

    public function faqAction(Request $request)
    {

        return $this->render('default/faq.html.twig', [
        ]);

    }

    /**
     * @Breadcrumb("breadcrumb.disclaimer.label", attributes={"translate": true})
     * @Route("/disclaimer", name="disclaimer")
     * @param Request $request
     * @return Response
     * @throws Exception
     */

    public function disclaimerAction(Request $request)
    {

        return $this->render('default/disclaimer.html.twig', [
        ]);

    }

    /**
     * @Breadcrumb("breadcrumb.parliament.label", attributes={"translate": true})
     * @Route("/parliament", name="parliament")
     * @param Request $request
     * @return Response
     * @throws Exception
     */

    public function parliamentAction(Request $request)
    {

        return $this->render('default/parliament.html.twig', [
        ]);

    }

    /**
     * @Route("/parliament/members", name="parliament_members", methods={"POST", "GET"}, options={"expose"=true})
     * @param Request $request
     * @return Response
     * @throws Exception
     * @throws \Psr\Cache\InvalidArgumentException
     */

    public function parliamentMembersAction()
    {
        $cacheKey = 'parliament_members';
        $cache = $this->cache->getItem($cacheKey);
        // $cache = $this->get('cache.app')->getItem('parliament_members');

        if (!$cache->isHit()) {

            $em = $this->managerRegistry->getManager();

            $delegations = $em->getRepository(User::class)
                ->getMostDelegationsByUser(20);

            $cache->set($delegations);
            $cache->expiresAfter(600);

        } else {
            $delegations = $cache->get();
        }

        return $this->createApiResponse([
            'success' => true,
            'data' => $delegations
        ]);

    }

    /**
     *
     * @Breadcrumb("breadcrumb.assembly.label", attributes={"translate": true})
     * @Route("/assembly", name="general_assembly")
     * @param Request $request
     * @return Response
     */
    public function assemblyAction(Request $request)
    {
        // replace this example code with whatever you need
        return $this->render('default/assembly.html.twig', [

        ]);
    }

    /**
     * Lists all users.
     *
     * @Route("/assembly/search", name="assembly_search", methods={"POST"},defaults={"id"=1},options={"expose"=true})
     * @param Request $request
     * @return JsonResponse
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function assemblySearchAction(Request $request)
    {

        $em = $this->managerRegistry->getManager();
        $draw = $request->request->getInt('draw', 1);
        $start = $request->request->getInt('start', 0);
        $length = $request->request->getInt('length', 10);
        $search = $request->request->get('search');
        $columns = $request->request->get('columns');
        $order = $request->request->get('order');
        $orderBy = $columns[$order[0]['column']]['data'];
        $orderDir = $order[0]['dir'];
        $orders = array(
            array($orderBy, $orderDir)
        );
        $users = $em->getRepository(User::class)->assemblySearch($search['value'], $orders);

        $output = array();
        $output['draw'] = $draw;
        $output['recordsTotal'] = $em->getRepository(User::class)->countAllUsers(true);
        $output["recordsFiltered"] = count($users);

        $output['items'] = array_splice($users, $start, $length);
        $response = $this->createApiResponse($output, 200);

        return $response;
    }


    /**
     * @Route("/test", name="test")
     * @param Request $request
     * @throws Exception
     */

    public function testAction(Request $request)
    {


        $em = $this->managerRegistry->getManager();
        $users = $em->getRepository(User::class)->getMostDelegationsByUser();

        exit();
    }

}

templates/default/assembly.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: 'General Assembly', background: '/assets/img/header/generalassembly_large.jpg'}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

    <div class="wpe-content-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="default-content bg-white mb-30 p-30 box-shadow">
                    <!-- Section Title -->
                    <div class="section-heading">
                        <h5>General Assembly</h5>
                    </div>
                    <table id="users" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                        <tr>
                            <th class="no-sort" style="width:50px"></th>
                            <th>Name</th>
                            <th>Country</th>
                            <th>City</th>
                            <th>Registered since</th>
                        </tr>
                        </thead>

                        <tbody>
                        </tbody>

                        <tfoot>
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Country</th>
                            <th>City</th>
                            <th>Registered since</th>

                        </tr>
                        </tfoot>

                    </table>

                </div>

            </div>
        </div>
    </div>

    <!-- ##### Delegation Area End ##### -->
</div>

{% endblock body %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="assets/plugins/DataTables/datatables.min.js"></script>
    <script type="text/javascript" >
        $(document).ready(function () {
            var app = App.getInstance();
            app.configureDTAssembly($('#users'));
        });
    </script>

{% endblock %}
{% block stylesheets %}
    {{ parent() }}

    <link rel="stylesheet" type="text/css" href="assets/plugins/DataTables/datatables.min.css"/>

{% endblock %}

templates/default/disclaimer.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: 'Disclaimer', background: asset('/assets/img/header/generalassembly_large.jpg')}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

    <div class="wpe-content-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="default-content bg-white mb-30 p-30 box-shadow">
                    <!-- Section Title -->

                    <div class="section-heading">
                        <h5>Terms and Conditions for the Beta Test of the World Parliament Experiment</h5>
                    </div>

                    <p>
                        By participating this website, you acknowledge that you have read, understood, and accepted the following terms and conditions.
                    </p>
                    <p>1. In no event shall World Parliament Experiment e.V. and Democracy Without Borders e.V. or their suppliers be liable for any damages whatsoever arising out of the use of or inability to use the World Parliament Experiment.</p>
                    <p>2. World Parliament Experiment e.V. can terminate the Beta Test at any time.</p>
                    <p>3. You acknowledge and agree that by participating in the Beta Test or by using the Beta Software World Parliament Experiment, World Parliament Experiment e.V. and Democracy Without Borders e.V. may receive certain information about you including personally identifiable information, and you hereby consent to World Parliament Experiment e.V.’s and Democracy Without Borders e.V.’s collection, use and disclosure of such information.</p>
                    <p>4. If you have questions please write an email to: team@world-parliament.org</p>
                </div>

            </div>
        </div>
    </div>

    <!-- ##### Delegation Area End ##### -->
</div>

{% endblock body %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!-- ##### Hero Area Start ##### -->

    {{ include ('/Widget/hero.html.twig', {votes: top}, with_context = false) }}
    {{ include ('Widget/_flashes-danger.html.twig', {flashes: app.flashes}, with_context = false) }}


    <!-- ##### Hero Area End ##### -->

    <!-- ##### Mag Posts Area Start ##### -->
    <section class="mag-posts-area d-flex flex-wrap">

        <!-- >>>>>>>>>>>>>>>>>>>>
         Post Left Sidebar Area
        <<<<<<<<<<<<<<<<<<<<< -->
        <div class="post-sidebar-area left-sidebar m-t-30 m-b-30 bg-white box-shadow">
            <!-- Sidebar Widget -->
            <div class="single-sidebar-widget p-30">
               {{ render(controller('AppBundle\\Controller\\WidgetController::MostPopularAction')) }}
            </div>
{#              <div class="single-sidebar-widget p-30">#}
{#                {{ render(controller('AppBundle:Widget:MostCommentedInitiatives')) }}#}
{#            </div>#}
            <div class="single-sidebar-widget p-30">
                {{ render(controller('AppBundle\\Controller\\WidgetController::MostViewsAction')) }}
            </div>
            <div class="single-sidebar-widget p-30">
                {{ render(controller('AppBundle\\Controller\\WidgetController::MostCommentsAction')) }}
            </div>
            <div class="single-sidebar-widget p-30">
                {{ render(controller('AppBundle\\Controller\\WidgetController::mostDelegationsAction')) }}
            </div>
            <div class="single-sidebar-widget p-30">
                {{ render(controller('AppBundle\\Controller\\WidgetController::MostInitiativesAction')) }}
            </div>


        </div>

        <!-- >>>>>>>>>>>>>>>>>>>>
             Main Posts Area
        <<<<<<<<<<<<<<<<<<<<< -->

        <div class="mag-posts-content m-t-30 m-b-30 p-30 box-shadow">
            <div class="feature-video-posts m-b-30">
                <!-- Section Title -->
                <div class="section-heading">
                    <h5>A global polity for the citizens of the world</h5>
                </div>
                <div class="post-content">
                    <p>The World Parliament Experiment (WPE) is a <b>positive vision</b> of a <b>fully democratic world</b>, in which everybody can take part and have a say. 
                    
                    <p><b>Global, digital, democratic.</b> </p>
                </div>
            </div>
            

           
            <!-- Feature Video Posts Area -->
            <div class="feature-video-posts m-b-30">
                <div class="section-heading">
                    <h5>Why do we need it?</h5>
                </div>
                  <p><b>War is not inevitable. </b> It is the result of the current political division of the world.
                  <p><b>Tyranny and injustice are not inevitable. </b> Rule of law is still not a reality for many people on earth. Tyrants are allowed to hide behind national sovereignty.
                  <p><b>Environmental destruction is not inevitable.</b> Our environment is a global public good. We will not succeed in protecting it by local legislation and covenants of goodwill only. 
                  <p><b>Poverty is not inevitable.</b> Global economic activity needs global standards and governance. Only in a global society of free citizens can the true potential of humankind be fulfilled.
                <br />
                <div class="section-heading">
                    <h5>Global Democracy is possible, if <u>YOU</u> take part in it!</h5>
                </div>
                    <p>The WPE allows you to create your own political proposals, both on the global and national level. You can also vote on real-world political initiatives.</p>         
                    <p>The WPE voting results will be visible to decision-making bodies both on the national and supra-national level. We aim to be a real political factor. The more people participate, the more powerful the voice of the WPE will become.</p>
                    <p>To start creating proposals, vote, discuss or be elected, <a href="{{ path("login") }}"> login</a> or create a <a href="{{ path("app_register") }}"> global citizen user account</a>. For detailed instructions and further information, please visit the <a href="{{ path("faq") }}">FAQ section</a>.</p>
                <br />
                <blockquote>
                    <h6 class="quote-text">“It is rather for us to be here dedicated to the great task remaining before us [...] that government of the people, by the people, for the people, shall not perish from the earth.”</h6>
                    <h6 class="quote-name">ABRAHAM LINCOLN</h6>
                </blockquote>
                <br />

            </div>
        </div>

        <!-- >>>>>>>>>>>>>>>>>>>>
        Post Right Sidebar Area
        <<<<<<<<<<<<<<<<<<<<< -->

        <div class="post-sidebar-area right-sidebar m-t-30 m-b-30 box-shadow">
            <div class="single-sidebar-widget p-30">
                {{ render(controller('AppBundle\\Controller\\WidgetController::CategoriesOverviewAction', { 'type': 'future' })) }}
            </div>
            <div class="single-sidebar-widget p-30">
                {{ render(controller('AppBundle\\Controller\\WidgetController::mostCitizensByCountryAction')) }}
            </div>
        </div> 

    </section>
    <!-- ##### Mag Posts Area End ##### -->

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/default/parliament.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: 'Virtual Parliament', background: '/assets/img/header/parliament_large.jpeg'}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

    <!-- ##### Delegation Area Start ##### -->
    <div class="wpe-content-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="default-content bg-white mb-30 p-30 box-shadow">
                        <!-- Section Title -->
                        <div class="section-heading">
                            <h5>Virtual Parliament</h5>
                        </div>

                        <p>At the moment the "Virtual Parliament" is build up by the TOP 20 users with the highest "Delegation Score".</p>

                        <div class="parliament pb-5">
                            <div class="circle-container"></div>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <!-- ##### Delegation Area End ##### -->
    </div>

{% endblock body %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {

            var app = App.getInstance();
            app.drawParliament($(".circle-container"));

        });

    </script>

{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}

templates/default/privacy.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: 'Privacy', background: asset('/assets/img/header/generalassembly_large.jpg')}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

<div class="wpe-content-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="default-content bg-white mb-30 p-30 box-shadow">
                    <!-- Section Title -->

                    <div class="section-heading">
                        <h5>Privacy</h5>
                    </div>

                    <h1>Coming soon.</h1>

                </div>

            </div>
        </div>
    </div>

    <!-- ##### Delegation Area End ##### -->
</div>

{% endblock body %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}

templates/default/quicksearch.html.twig
{% extends "base.html.twig" %}

{% block body %}

    {{ include ('Widget/_breadcrumb.html.twig', {title: 'Search', background: asset('/assets/img/header/initiative_large.jpg')}, with_context = false) }}

    {{ apy_breadcrumb_trail_render() }}

    {{ include ('Widget/_flashes.html.twig', {flashes: app.flashes}, with_context = false) }}

    <div class="wpe-content-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="default-content bg-white p-30 mb-30 box-shadow">
                        <!-- Section Title -->
                        <div class="section-heading">
                            <h5>{{ 'quicksearch.page_title'|trans }}</h5>
                        </div>
                        {% if token_error %}
                            <p class="alert alert-danger">{{ 'quicksearch.token_error'|trans }}</p>
                        {% endif %}
                        {{ form_start(form) }}
                        <input type="hidden" name="search_token" id="topToken" value="{{ csrf_token('top-search') }}">

                        {{ form_row(form.query)}}

                        <button type="submit" class="btn btn-primary" formnovalidate><i class="fa fa-save"></i> {{ 'quicksearch.button.submit'|trans }} </button>
                        {{ form_end(form) }}
                        <br>

                        {% if valid %}
                            {% if  initiatives|length == 0%}
                            <p class="alert alert-info">{{ 'quicksearch.no_matches'|trans }}</p>
                            {% else %}
                            <table id="initiatives" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>type</th>
                                        <th>category</th>
                                        <th>name</th>
                                        <th>user</th>
                                        <th>published</th>
                                    </tr>
                                </thead>

                                <tbody>
                                {% for initiative in initiatives %}
                                    <tr>
                                        <td>{{ initiative.typeName }}</td>
                                        <td>{{ initiative.category.name }}</td>
                                        <td>
                                            <a href="{{ path('initiative_show', { 'id': initiative.id ,'slug': initiative.slug}) }}">{{ initiative.title }}</a>
                                        </td>
                                        <td><a href="{{ path('user_profile_show', { 'id':initiative.createdBy.id }) }}" class="author-name">{{ initiative.createdBy.username }}</a></td>
                                        <td>{{ initiative.publishedAt|date('d.m.Y H:i') }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>

                                <tfoot>
                                    <tr>
                                        <th>type</th>
                                        <th>category</th>
                                        <th>name</th>
                                        <th>user</th>
                                        <th>published</th>
                                    </tr>
                                </tfoot>

                            </table>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/assets/plugins/DataTables/datatables.min.css') }}"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('/assets/plugins/DataTables/datatables.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            const table = $('#initiatives').DataTable({
                responsive: false,
                autoWidth: true,
                "processing": true,
                "serverSide": false,
                "searching": true,
                "ordering": true,
                "order": [[0, "asc"]],
                deferRender: true,
            });
        });
    </script>

{% endblock %}

templates/default/trending.html.twig
{% for votec in votesr %}
    <!-- Single Trending Post -->
    <div class="single-trending-post">
        <img src="{{ asset(votec.category.imageSmall) }}" alt=""/>
        <div class="post-content">
            <a href="#" class="post-cata">{{ votec.category.name }}</a>
            <a href="{{ path('initiative_show', { 'id': votec.id, 'slug': votec.slug }) }}" class="post-title">{{ votec.title }}</a> <br>
        </div>
    </div>
{% endfor %}